version: '3'
services:
  postgresql:
    image: postgres:9.4
    restart: always
    networks:
      - spring-boot-postgresql-network
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dev
    ports:
      - '5432:5432'
    volumes:
      - ./src/main/resources/db/:/docker-entrypoint-initdb.d/
  bank-service:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - spring-boot-postgresql-network
    depends_on:
      - postgresql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/dev
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
networks:
    spring-boot-postgresql-network:
      driver: bridge